/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edusys_ui;

import DAO.DAOChuyenDe;
import DAO.DAOInterface;
import Entitys.ChuyenDe;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import utils.Auth;
import utils.Check;
import utils.Helper;
import utils.XImage;

/**
 *
 * @author Thang
 */
public class QLChuyenDeJInternalFrame extends javax.swing.JInternalFrame {

    int index;
    static DAOInterface daoCD = new DAOChuyenDe();
    DefaultTableModel tableModel;
    ArrayList<ChuyenDe> chuyenDeList = new ArrayList<>();
    boolean specifyBtnMoi;

    /**
     * Creates new form QLChuyenDeJInternalFrame
     */
    public QLChuyenDeJInternalFrame() {
        initComponents();
        customTable();
        setting();
        if (chuyenDeList.size() > 0) {
            index = 0;
            fillToForm(index);
        }

    }

    private void setting() {
        tblBang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        specifyBtnMoi = true;
        disableComponent(btnThem, txtMaCD);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtThoiLuong = new javax.swing.JTextField();
        btn4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        lblRecord = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAnh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaCD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn2 = new javax.swing.JButton();
        txtTenCD = new javax.swing.JTextField();
        btn3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setClosable(true);
        setIconifiable(true);

        btn4.setText(">|");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Thời lượng (giờ)");

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        jLabel6.setText("Học phí");

        txtHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHocPhiActionPerformed(evt);
            }
        });

        lblRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecord.setText("jLabel7");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btn1.setText("|<");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý chuyên đề");

        jLabel2.setText("Hình Logo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), null));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(230, 260));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        lblAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnh.setText("Chọn ảnh");
        lblAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAnhMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Mã chuyên đề");

        jLabel4.setText("Tên chuyên đề");

        btn2.setText("<<");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText(">>");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Mô tả");

        txtMoTa.setColumns(20);
        txtMoTa.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtMoTa.setLineWrap(true);
        txtMoTa.setRows(5);
        txtMoTa.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtMoTa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(31, 31, 31)
                                .addComponent(lblRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btn1)
                                .addGap(18, 18, 18)
                                .addComponent(btn2)
                                .addGap(18, 18, 18)
                                .addComponent(btn3)
                                .addGap(18, 18, 18)
                                .addComponent(btn4)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaCD, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenCD, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThoiLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMaCD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnXoa)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(lblRecord))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btnLast();
    }//GEN-LAST:event_btn4ActionPerformed

    private void tblBangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMousePressed
        // TODO add your handling code here:.
        index = tblBang.getSelectedRow();
        fillToForm(index);
    }//GEN-LAST:event_tblBangMousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String arr[] = {"Mã CD", "Tên CD", "Học phí", "Thời lượng", "Hình"};

        ChuyenDe chuyenDe = getForm();
        int success = daoCD.insertToDB(chuyenDe);
        if (success > 0) {
            JOptionPane.showMessageDialog(null, "Thêm chuyên đề thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            chuyenDeList.add(chuyenDe);
            tableModel.addRow(new Object[]{
                chuyenDe.getMaCD(), chuyenDe.getTenCD(), chuyenDe.getHocPhi(), chuyenDe.getThoiLuong(), chuyenDe.getHinh()
            });
            index = tableModel.getRowCount() - 1;
            fillToForm(index);
            btnMoi.setText("Mới");
            System.out.println(index);
            disableComponent(btnThem);
            enableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua);
            txtMaCD.setEnabled(false);
            specifyBtnMoi = true;
        } else {
            JOptionPane.showMessageDialog(null, "Thêm chuyên đề không thành công", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ChuyenDe chuyenDe = getForm();
        index = tblBang.getSelectedRow();
        if (chuyenDe != null) {
            int success = daoCD.updateToDB(chuyenDe);
            if (success > 0) {
                JOptionPane.showMessageDialog(null, "Cập nhật thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                chuyenDeList.set(index, chuyenDe);
//                tblBang.setValueAt(chuyenDe.getMaCD(), index, 0);
                tblBang.setValueAt(chuyenDe.getTenCD(), index, 1);
                tblBang.setValueAt(chuyenDe.getThoiLuong(), index, 3);
                tblBang.setValueAt(chuyenDe.getHocPhi(), index, 2);
                tblBang.setValueAt(chuyenDe.getHinh(), index, 4);
            } else {
                JOptionPane.showMessageDialog(null, "Cập nhật thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed

        if (specifyBtnMoi) {
            index = tblBang.getSelectedRow();
            clearForm();
            btnMoi.setText("Hủy");
            disableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua);
            enableComponent(btnThem, txtMaCD);
            specifyBtnMoi = false;
        } else {
            btnMoi.setText("Mới");
            System.out.println(index);
            enableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua);
            disableComponent(btnThem, txtMaCD);
            specifyBtnMoi = true;
            fillToForm(index);
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnFirst();
    }//GEN-LAST:event_btn1ActionPerformed

    private void lblAnhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhMousePressed
        // TODO add your handling code here:
        jPanel1MousePressed(evt);
    }//GEN-LAST:event_lblAnhMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        chonAnh();
    }//GEN-LAST:event_jPanel1MousePressed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btnPrevious();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btnNext();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (Auth.getRole()) {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa chuyên đề " + txtMaCD.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                index = tblBang.getSelectedRow();
                ChuyenDe cd = chuyenDeList.get(index);
                int success = daoCD.delete(txtMaCD.getText());
                if (success > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    chuyenDeList.remove(index);
                    tableModel.removeRow(index);
                    if (tableModel.getRowCount() == 0) {
                        clearForm();
                    } else if (tableModel.getRowCount() == index) {
                        index--;
                        fillToForm(index);
                    } else {
                        fillToForm(index);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa không thành công", "Thông báo", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn không có quyền xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHocPhiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHocPhiActionPerformed
    private void chonAnh() {
        JFileChooser jfc = new JFileChooser();
        jfc.setCurrentDirectory(new File(System.getProperty("user.dir") + "\\images")); // Lấy vị trị của project khi mở chooser
        FileFilter filter = new FileNameExtensionFilter("Image file", ImageIO.getReaderFileSuffixes());
        jfc.setFileFilter(filter);
        jfc.setAcceptAllFileFilterUsed(false); // Cho phép chọn các file ngoài filter 
        int chooser = jfc.showOpenDialog(this);
        if (chooser == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            System.out.println(f.toString());
            XImage.save(f);
            ImageIcon icon = XImage.read(f.getName());
            icon = scaleImage(icon);

            lblAnh.setText("");
            System.out.println(f.getAbsolutePath());
            lblAnh.setIcon(icon);
            lblAnh.setToolTipText(f.getName()); // Khi hover sẽ hiện tên của file được chọn
        } else {
            lblAnh.setIcon(null);
            lblAnh.setText("Chọn ảnh");
            lblAnh.setToolTipText(null);
        }
    }

    private ImageIcon scaleImage(ImageIcon icon) {
        if (icon.getImage().getWidth(null) > 189 && icon.getImage().getHeight(null) > 233) { // scale if width and height over allowed 
            Image image = icon.getImage().getScaledInstance(189, 233, Image.SCALE_SMOOTH);
            icon = new ImageIcon(image);
        }
        return icon;
    }

    private void btnFirst() {
        if (index == 0) {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi đầu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {

            index = 0;
            fillToForm(index);
//        btn1.setEnabled(false);
        }
    }

    private void btnPrevious() {
        if (index > 0) {
            index--;
            fillToForm(index);
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi đầu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnNext() {
        if (index < chuyenDeList.size() - 1) {
            index++;
            fillToForm(index);
//            btn1.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi cuối", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnLast() {
        if (index == chuyenDeList.size() - 1) {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi cuối", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
//            btn1.setEnabled(true);
        } else {
            index = chuyenDeList.size() - 1;
            fillToForm(index);
        }
    }

    private void disableComponent(JComponent... components) {
        for (JComponent component : components) {
            component.setEnabled(false);
        }
    }

    private void enableComponent(JComponent... components) {
        for (JComponent component : components) {
            component.setEnabled(true);
        }
    }

    private void customTable() {
        String arr[] = {"Mã CD", "Tên CD", "Học phí", "Thời lượng", "Hình"};
        tableModel = new DefaultTableModel(arr, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        tblBang.setModel(tableModel);
        fillToTable();
    }

    private void fillToTable() {
        chuyenDeList = daoCD.getAll();
        tableModel.setRowCount(0);
        for (ChuyenDe cd : chuyenDeList) {
            tableModel.addRow(new Object[]{
                cd.getMaCD(), cd.getTenCD(), cd.getHocPhi(), cd.getThoiLuong(), cd.getHinh()
            });
        }
    }

    private void fillToForm(int i) {
        txtMaCD.setText(chuyenDeList.get(i).getMaCD());
        txtTenCD.setText(chuyenDeList.get(i).getTenCD());
        txtHocPhi.setText(chuyenDeList.get(i).getHocPhi() + "");
        txtThoiLuong.setText(chuyenDeList.get(i).getThoiLuong() + "");
        txtMoTa.setText(chuyenDeList.get(i).getMoTa());
//        if(chuyenDeList.get(i).getHinh()== null){
//                        System.out.println("1");
//
//        }
        if (!chuyenDeList.get(i).getHinh().trim().equals("")) {
            lblAnh.setIcon(scaleImage(XImage.read(chuyenDeList.get(i).getHinh())));
            lblAnh.setToolTipText(chuyenDeList.get(i).getHinh());
            lblAnh.setText("");
        } else {
            lblAnh.setText("Chọn ảnh");
            lblAnh.setIcon(null);
            lblAnh.setToolTipText(null);
            System.out.println("1" + lblAnh.getToolTipText());
        }
        tblBang.setRowSelectionInterval(i, i);
        lblRecord.setText((i + 1) + " / " + (chuyenDeList.size()));
    }

    private void clearForm() {
        txtMaCD.setText("");
        txtTenCD.setText("");
        txtHocPhi.setText("");
        txtThoiLuong.setText("");
        lblRecord.setText("? / " + (chuyenDeList.size()));
        lblAnh.setText("Chọn ảnh");
        lblAnh.setToolTipText(null);
        lblAnh.setIcon(null);
        tblBang.getSelectionModel().clearSelection();
    }

    private ChuyenDe getForm() {
        if (check()) {
            String ma = txtMaCD.getText().trim(), ten = txtTenCD.getText().trim(), hocPhi = txtHocPhi.getText().trim(), thoiLuong = txtThoiLuong.getText().trim(),
                    moTa = txtMoTa.getText().trim(), hinh = lblAnh.getToolTipText();
            if (hinh == null) {
                hinh = "";
            }
            int tl = Helper.parseInt(thoiLuong);
            double hp = Helper.parseDouble(hocPhi);
            return new ChuyenDe(ma, ten, hinh, moTa, (float) hp, tl);
        }
        return null;
    }

    private boolean check() {
        String ma = txtMaCD.getText().trim(), ten = txtTenCD.getText().trim(), hocPhi = txtHocPhi.getText().trim(), thoiLuong = txtThoiLuong.getText().trim(), moTa = txtMoTa.getText().trim();
        if (!Check.checkNull(ma, ten, hocPhi, thoiLuong)) {
            JOptionPane.showMessageDialog(this, "Nhập đủ dữ liệu", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(1, 5, ma)) {
            JOptionPane.showMessageDialog(this, "Mã CD từ 1 - 5 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(1, 50, ten)) {
            JOptionPane.showMessageDialog(this, "Tên NV từ 1 - 50 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(0, 255, moTa)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu từ 0 - 255 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.isANumberInteger(thoiLuong)) {
            JOptionPane.showMessageDialog(this, "Thời lượng là 1 số nguyên", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.isANumberDouble(hocPhi)) {
            JOptionPane.showMessageDialog(this, "Học phí là 1 số", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtMaCD;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtTenCD;
    private javax.swing.JTextField txtThoiLuong;
    // End of variables declaration//GEN-END:variables
}
