/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edusys_ui;

import DAO.DAOInterface;
import DAO.DAONhanVien;
import Entitys.NhanVien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import utils.Auth;
import utils.Check;

/**
 *
 * @author Thang
 */
public class QLNhanVienInternalFrame extends javax.swing.JInternalFrame {

    static DAOInterface daonv = new DAONhanVien();
    int index;
    DefaultTableModel tableModel;
    DefaultComboBoxModel<String> comboBoxModel;
    List<NhanVien> nhanVienList = new ArrayList<>();
    boolean specifyBtnMoi;

    /**
     * Creates new form QLChuyenDeJInternalFrame
     */
    public QLNhanVienInternalFrame() {
        initComponents();
        add();
        customTable();
        customComboBox();
        if (nhanVienList.size() > 0) {
            index = 0;
            fillToForm(index);
        }

    }

    private void add() {
        tblBang.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        nhanVienList = daonv.getAll();
        specifyBtnMoi = true;
        disableComponent(btnThem, txtMa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        itemYes = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang = new javax.swing.JTable();
        lblRecord = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtXN = new javax.swing.JTextField();
        rdoTP = new javax.swing.JRadioButton();
        rdoNV = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        cbXem = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        itemYes.setText("jMenuItem1");
        itemYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemYesActionPerformed(evt);
            }
        });
        jPopupMenu1.add(itemYes);

        setClosable(true);
        setIconifiable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý nhân viên");

        jLabel3.setText("Mã nhân viên");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btn1.setText("|<");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("<<");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText(">>");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText(">|");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        tblBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblBangMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang);

        lblRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecord.setText("jLabel7");

        jLabel7.setText("Mật khẩu");

        jLabel9.setText("Xác nhận ");

        buttonGroup1.add(rdoTP);
        rdoTP.setSelected(true);
        rdoTP.setText("Trưởng phòng");

        buttonGroup1.add(rdoNV);
        rdoNV.setText("Nhân viên");

        jLabel11.setText("Vai trò");

        jLabel12.setText("Họ và tên");

        cbXem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbXem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbXemItemStateChanged(evt);
            }
        });

        jLabel14.setText("Chế độ xem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnMoi)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbXem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addComponent(lblRecord, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn1)
                        .addGap(18, 18, 18)
                        .addComponent(btn2)
                        .addGap(18, 18, 18)
                        .addComponent(btn3)
                        .addGap(18, 18, 18)
                        .addComponent(btn4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMK, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtXN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdoTP)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNV)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtXN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTP)
                    .addComponent(rdoNV)
                    .addComponent(jLabel11))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnMoi)
                    .addComponent(btnXoa)
                    .addComponent(btn1)
                    .addComponent(btn2)
                    .addComponent(btn3)
                    .addComponent(btn4)
                    .addComponent(lblRecord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbXem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        NhanVien nhanVien = getForm();
        if (nhanVien != null) {
            int isSuccess = daonv.insertToDB(nhanVien);
            if (isSuccess > 0) {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                nhanVienList.add(nhanVien);
                tableModel.addRow(new Object[]{
                    nhanVien.getMaNV(), nhanVien.getMatKhau(), nhanVien.getHoTen(), nhanVien.isVaiTro() ? "Trưởng phòng" : "Nhân viên"
                });
                index = tableModel.getRowCount() - 1;
                btnMoi.setText("Mới");
                System.out.println(index);
                disableComponent(btnThem);
                enableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua);
                txtMa.setEnabled(false);
                specifyBtnMoi = true;
                fillToForm(index);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm nhân viên thất bại", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        NhanVien nhanVien = getForm();
        if (nhanVien != null) {
            int isSuccess = daonv.updateToDB(nhanVien);
            if (isSuccess > 0) {
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                nhanVienList.set(index, nhanVien);
                tableModel.setValueAt(nhanVien.getHoTen(), index, 2);
                tableModel.setValueAt(nhanVien.getMatKhau(), index, 1);
                tableModel.setValueAt(nhanVien.isVaiTro() ? "Trưởng phòng" : "Nhân viên", index, 3);
                //                index = tableModel.getRowCount()-1;
                //                fillToForm(index);
            } else {
                JOptionPane.showMessageDialog(this, "Sửa nhân viên thất bại . Vui lòng xem lại dự liệu .", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        if (specifyBtnMoi) {
            index = tblBang.getSelectedRow();
            clearForm();
            btnMoi.setText("Hủy");
            disableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua, cbXem);
            enableComponent(btnThem, txtMa);
            specifyBtnMoi = false;
            System.out.println(index);
        } else {
            btnMoi.setText("Mới");
            System.out.println(index);
            disableComponent(btnThem, txtMa);
            enableComponent(btn1, btn2, btn3, btn4, btnXoa, btnSua, cbXem);
            specifyBtnMoi = true;
            fillToForm(index);
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnFirst();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        btnPrevious();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        btnNext();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        btnLast();

    }//GEN-LAST:event_btn4ActionPerformed

    private void tblBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblBangMouseClicked

    private void tblBangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMousePressed
        // TODO add your handling code here:
        index = tblBang.getSelectedRow();
        fillToForm(index);
    }//GEN-LAST:event_tblBangMousePressed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:

        NhanVien nhanVien = getForm();
        index = tblBang.getSelectedRow();
        if (nhanVien != null) {
            if (nhanVien.getMaNV().equalsIgnoreCase(Auth.nv.getMaNV())) {
                JOptionPane.showMessageDialog(this, "Không thể xóa chính mình .", "Thông báo", JOptionPane.WARNING_MESSAGE);

            } else {
                int option = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên " + txtMa.getText(), "Thông báo", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    nhanVien.setTrangThai(true);
                    int isSuccess = daonv.updateToDB(nhanVien);
                    if (isSuccess > 0) {
                        JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        nhanVienList.remove(index);
                        tableModel.removeRow(index);
                        if (tableModel.getRowCount() == index) {
                            index--;
                            fillToForm(index);
                        }
                        fillToForm(index);
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa nhân viên thất bại . Vui lòng xem lại dự liệu .", "Thông báo", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbXemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbXemItemStateChanged
        // TODO add your handling code here:
        if (cbXem.getSelectedIndex() == 0) {
            enableComponent(btnSua, btnMoi, btnXoa);
            enableComponent(btn1, btn2, btn3, btn4);
            nhanVienList.clear();
            nhanVienList = daonv.getAll();
            fillToTable();
            fillToForm(index);
        } else {
            nhanVienList.clear();
            nhanVienList = new DAONhanVien().getNAll();
            disableComponent(btnSua, btnMoi, btnXoa);
            fillToTable();
            if (nhanVienList.size() > 0) {
                fillToForm(0);
            } else {
                disableComponent(btn1, btn2, btn3, btn4);
                clearForm();
            }
        }
    }//GEN-LAST:event_cbXemItemStateChanged

    private void tblBangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangMouseReleased
        // TODO add your handling code here:
        if (cbXem.getSelectedIndex() != 0) {
            if (evt.isPopupTrigger()) {
                itemYes.setText("Khôi phục");
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tblBangMouseReleased

    private void itemYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemYesActionPerformed
        // TODO add your handling code here:
        index = tblBang.getSelectedRow();
        System.out.println("" + tblBang.getRowCount());
        NhanVien nhanVien = nhanVienList.get(index);
        if (nhanVien != null) {
            nhanVien.setTrangThai(false);
            int isSuccess = daonv.updateToDB(nhanVien);
            if (isSuccess > 0) {
                JOptionPane.showMessageDialog(this, "Khôi phục nhân viên thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                nhanVienList.remove(index);
                tableModel.removeRow(index);
                System.out.println(tblBang.getRowCount() + " - " + index);
                if (tableModel.getRowCount() == 0) {
                    disableComponent(btn1, btn2, btn3, btn4);
                    clearForm();
                } else if (tableModel.getRowCount() == index) {
                    index--;
                    fillToForm(index);
                } else {
                    System.out.println("index");
                    fillToForm(index);
                }

//                tableModel.setValueAt(nhanVien.getHoTen(), index, 2);
//                tableModel.setValueAt(nhanVien.getMatKhau(), index, 1);
//                tableModel.setValueAt(nhanVien.isVaiTro() ? "Trưởng phòng" : "Nhân viên", index, 3);
                //                index = tableModel.getRowCount()-1;
                //                fillToForm(index);
            } else {
                JOptionPane.showMessageDialog(this, "Khôi phục nhân viên thất bại . Vui lòng xem lại dự liệu .", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_itemYesActionPerformed
    private void customTable() {
        String arr[] = {"Mã NV", "Mật khẩu", "Họ tên", "Vai trò"};
        tableModel = new DefaultTableModel(arr, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }

        };
        tblBang.setModel(tableModel);
        fillToTable();
    }

    private void customComboBox() {
        String arr[] = {"Đang làm", "Đã nghỉ"};
        comboBoxModel = new DefaultComboBoxModel<>(arr);
        cbXem.setModel(comboBoxModel);
    }

    private void fillToTable() {

        tableModel.setRowCount(0);
        for (NhanVien nhanVien : nhanVienList) {
            tableModel.addRow(new Object[]{
                nhanVien.getMaNV(), nhanVien.getMatKhau(), nhanVien.getHoTen(), nhanVien.isVaiTro() ? "Trưởng phòng" : "Nhân viên"
            });
        }
    }

    private void fillToForm(int i) {
        txtMa.setText(nhanVienList.get(i).getMaNV());
        txtTen.setText(nhanVienList.get(i).getHoTen());
        txtMK.setText(nhanVienList.get(i).getMatKhau());
        txtXN.setText(nhanVienList.get(i).getMatKhau());
        if (nhanVienList.get(i).isVaiTro()) {
            rdoTP.setSelected(true);
        } else {
            rdoNV.setSelected(true);
        }
        tblBang.setRowSelectionInterval(i, i);
        lblRecord.setText((index + 1) + " / " + (nhanVienList.size()));
    }

    private void clearForm() {
        txtMa.setText("");
        txtMK.setText("");
        txtXN.setText("");
        txtTen.setText("");
        rdoTP.setSelected(true);
        lblRecord.setText("? / " + (nhanVienList.size()));
        tblBang.getSelectionModel().clearSelection();

    }

    private NhanVien getForm() {

        if (check()) {
            String ma = txtMa.getText().trim(), ten = txtTen.getText().trim(), matkhau = txtMK.getText().trim(), xacnhan = txtXN.getText().trim();
            return new NhanVien(txtMa.getText().trim(), txtTen.getText().trim(), txtMK.getText().trim(), rdoTP.isSelected());
        }
        return null;

    }

    private boolean check() {
        String ma = txtMa.getText().trim(), ten = txtTen.getText().trim(), matkhau = txtMK.getText().trim(), xacnhan = txtXN.getText().trim();
        if (!Check.checkNull(ma, ten, matkhau, xacnhan)) {
            JOptionPane.showMessageDialog(this, "Nhập đủ dữ liệu", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(1, 20, ma)) {
            JOptionPane.showMessageDialog(this, "Mã NV từ 1 - 20 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(1, 50, ten)) {
            JOptionPane.showMessageDialog(this, "Tên NV từ 1 - 50 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkLength(1, 50, matkhau)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu từ 1 - 50 ký tự", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        } else if (!Check.checkTrung(matkhau, xacnhan)) {
            JOptionPane.showMessageDialog(this, "Mật khẩu và xác nhận không trùng khớp", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;

    }

    private void btnFirst() {
        if (index == 0) {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi đầu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } else {

            index = 0;
            fillToForm(index);
//        btn1.setEnabled(false);
        }
    }

    private void btnPrevious() {
        if (index > 0) {
            index--;
            fillToForm(index);
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi đầu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnNext() {
        if (index < nhanVienList.size() - 1) {
            index++;
            fillToForm(index);
//            btn1.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi cuối", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void btnLast() {
        if (index == nhanVienList.size() - 1) {
            JOptionPane.showMessageDialog(this, "Đã đến bản ghi cuối", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
//            btn1.setEnabled(true);
        } else {
            index = nhanVienList.size() - 1;
            fillToForm(index);
        }
    }

    private void disableComponent(JComponent... components) {
        for (JComponent component : components) {
            component.setEnabled(false);
        }
    }

    private void enableComponent(JComponent... components) {
        for (JComponent component : components) {
            component.setEnabled(true);
        }
    }

//    private void disableTxt(JTextField... txt) {
//        for (JTextField jTextField : txt) {
//            jTextField.setEnabled(false);
//        }
//    }
//
//    private void enableTxt(JTextField... txt) {
//        for (JTextField jTextField : txt) {
//            jTextField.setEnabled(true);
//        }
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbXem;
    private javax.swing.JMenuItem itemYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRecord;
    private javax.swing.JRadioButton rdoNV;
    private javax.swing.JRadioButton rdoTP;
    private javax.swing.JTable tblBang;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtXN;
    // End of variables declaration//GEN-END:variables
}
